
---
title: "Earnings - SelectInput"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
df <- read_csv("Forbes Richest Atheletes (Forbes Richest Athletes 1990-2020).csv")
df <- df %>%  mutate(earnings =`earnings ($ million)`)

earnings_sport <- unique(df$Sport)
```

{.sidebar}
=======================================================================

Athletes have some of the highest wages worldwide.  These earnings can vary across sports and countries.This data set shows the top 100 athlete earnings worldwide. 

```{r}
selectInput(inputId = "sport_input", 
            label = h3("Select Sport"),
            choices = earnings_sport, 
            selected = 'NBA')
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(Sport==input$sport_input) %>% 
    ggplot(aes(x=earnings))+
    geom_density()
  ggplotly(p1)
})
```


