
---
title: "Earnings - Check Box"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    social: menu

runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(tidyverse)
library(plotly)
library(knitr)
library(DT)
library(lubridate)
df <- read_csv("Forbes Richest Atheletes (Forbes Richest Athletes 1990-2020).csv")

df <- df %>%  mutate(earnings =`earnings ($ million)`)
df$date <- mdy(df$date)
unique_sport <- unique(df$Sport)
```

{.sidebar}
=======================================================================

- Athletes have some of the highest wages worldwide.  These earnings can vary across sports and countries. This data set shows the top 100 athlete earnings worldwide.  Select the input for the plots. 

- In this example, the data for Date is not fictional and not real data. 

```{r}
dateRangeInput(inputId = "date_input", 
               label = h2("Date range"), 
               start = min(df$date), 
               end = max(df$date),
               min = min(df$date), 
               max = max(df$date))
```

Main Tab 1
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot

```{r}
renderPlotly({
  p1 <- df %>% 
    filter(date > input$date_input[1], date < input$date_input[2]) %>% 
    ggplot(aes(x=earnings))+
    geom_density()
  ggplotly(p1)
})
```
